
import = [
    "./everforest-scheme.toml"
]


[colors.bright]
black = "#626262"
blue = "#add4fb"
cyan = "#87d7d7"
green = "#87af87"
magenta = "#ffafaf"
red = "#d75f87"
white = "#e4e4e4"
yellow = "#ffd787"

[colors.normal]
black = "#4e4e4e"
blue = "#85add4"
cyan = "#87afaf"
green = "#5f865f"
magenta = "#d7afaf"
red = "#d68787"
white = "#d0d0d0"
yellow = "#d8af5f"

[colors.primary]
background = "#3a3a3a"
foreground = "#d0d0d0"

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "alacritty"

[font]
size = 8.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "medium"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_title = true
opacity = 1
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 200
lines = 50

[window.padding]
x = 10
y = 10
