
# SYM

## Esc. -> Escape
## F1 -> XF86AudioMute              (Volume 0)
## F2 -> XF86AudioLowerVolume       (Volume -)
## F3 -> XF86AudioRaiseVolume       (Volume +)
## F4 -> XF86AudioMicMute           (Mic 0)
## F5 -> XF86MonBrightnessDown      (Bright -)
## F6 -> XF86MonBrightnessUp        (Bright +)
## F7 -> SUPER + P                  (Undefined - [ScreenSharing by default])
## F8 -> XF86RFKill     (System management - Don't touch)
## F9 -> SUPER + I                  (Undefined - [Settings])
## F10 -> SUPER + L                 (Lock Session)
## F11 -> SUPER + V                 (ToogleFloating)
## F12 -> XF86Calculator            (Undefined - [Calculator])
## Ins -> XF86Favorites             (Undefined - [Favorites])
## ImpPt -> SUPER + SHIFT + S       (Screenshots)
## Supr -> Delete

source = ./variables.conf

$mod = SUPER

# Generals

# Function (Fn) keys
bind = $mod SHIFT, S, exec, mkdir -p ~/Pictures/Screenshots && grim -g "$(slurp)" ~/Pictures/Screenshots/screenshot_$(date +%Y%m%d_%H%M%S).png && wl-copy < ~/Pictures/Screenshots/screenshot_$(date +%Y%m%d_%H%M%S).png

# Focus movement
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

# Workspace switching

# Move window to workspace
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

# Mouse bindings
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow


