
# compatible version: 0.53.4 (last review 06/04/2026)

source = ./hyprland/env.conf

source = ./hyprland/main.conf

source = ./hyprland/ui.conf
source = ./hyprland/io.conf

source = ./hyprland/keybinds.conf
source = ./hyprland/windowrules.conf

