
# SYM

## Esc. -> Escape
## F1 -> XF86AudioMute              (Volume 0)
## F2 -> XF86AudioLowerVolume       (Volume -)
## F3 -> XF86AudioRaiseVolume       (Volume +)
## F4 -> XF86AudioMicMute           (Mic 0)
## F5 -> XF86MonBrightnessDown      (Bright -)
## F6 -> XF86MonBrightnessUp        (Bright +)
## F7 -> SUPER + P                  (Undefined - [ScreenSharing by default])
## F8 -> XF86RFKill     (System management - Don't touch)
## F9 -> SUPER + I                  (Undefined - [Settings])
## F10 -> SUPER + L                 (Lock Session)
## F11 -> SUPER + V                 (ToogleFloating)
## F12 -> XF86Calculator            (Undefined - [Calculator])
## Ins -> XF86Favorites             (Undefined - [Favorites])
## ImpPt -> SUPER + SHIFT + S       (Screenshots)
## Supr -> Delete

source = ./variables.conf

$mod = SUPER

# Generals
bind = $mod, E, exec, $menu
bind = $mod, W, exec, $terminal
bind = $mod, C, killactive,
bind = $mod, V, togglefloating,
bind = $mod, L, exec, loginctl lock-session

# Function (Fn) keys
## Volumen
bind = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+		# Rise
bind = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-		# Down
bind = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle			    # Mute
## Brightness
bind = , XF86MonBrightnessDown, exec, bash -c 'curr=$(brightnessctl get); new=$((curr*2/3)); brightnessctl set ${new}'      # Rise
bind = , XF86MonBrightnessUp, exec, bash -c 'curr=$(brightnessctl get); new=$((curr*4/3)); brightnessctl set ${new}'        # Down
## Screenshots
bind = $mod SHIFT, S, exec, mkdir -p ~/Pictures/Screenshots && grim -g "$(slurp)" ~/Pictures/Screenshots/screenshot_$(date +%Y%m%d_%H%M%S).png && wl-copy < ~/Pictures/Screenshots/screenshot_$(date +%Y%m%d_%H%M%S).png

# Focus movement
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

# Workspace switching
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

# Move window to workspace
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

# Mouse bindings
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow


