
monitor=eDP-1,highres@60,auto,1.6

exec-once = systemctl --user start hyprpolkitagent
# exec-once = dunst

exec-once = hyprpaper &
exec-once = sleep 0.1 && sh $HOME/Documents/dotFiles/scripts/wallpaperHandler.sh

exec-once = quickshell

exec-once = hypridle
