
general {
    border_size = 0
    gaps_in = 6
    gaps_out = 12
    layout = dwindle
    resize_on_border = true
}

decoration {
rounding = 16
    blur {
        enabled = true
        new_optimizations = true
    }
    shadow {
        range = 80
        color = rgba(00000043)
        color_inactive = rgba(00000030)
    }
}

animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# Layout
dwindle {
    # pseudotile = true
    preserve_split = true
}
# XWayland
## HuDPI XWayland
xwayland {
	force_zero_scaling = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}
